# curl -H 'Authorization: Bearer dac6164cd0cf4ea6b539aa2a6a1f457d' --json '{"start_time": "2023-1-31T23:00:00.000Z", "end_time": "2023-2-22T23:00:00.000Z", "sum_hours": 24}' http://csi420-02-vm8.ucd.ie/api/v1/profile/1/usage
openapi: 3.0.0
info:
  title: Restful API documentation
  description: Experimental API DOC. Some endpoint may not work. TODO update to the newest stage.
  version: 0.1.0
servers:
  - url: http://csi420-02-vm8.ucd.ie/api/v1
  
paths:
  /user/profiles:
    get:
      summary: Get all profiles of a user.
      description: Profile means somethings like factory electricity usage management (it has usage, solar, etc. data). A user can have many profiles.
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/profile'
      tags:
        - user
        - profile
        - electricity
        
  /profile/{profileId}:
    get:
      summary: get specifc profile
      parameters:
        - $ref: '#/components/parameters/profileId'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/profile'
                
      tags:
        - profile
        - electricity
        
  /profile/{profileId}/usage:
    post:
      summary: usage data
      description: Get the corresponding usage data of a profile.
      parameters:
        - $ref: '#/components/parameters/profileId'
      requestBody:
        $ref: '#/components/requestBodies/time_interval'
      responses:
        '200':
          description: 'success'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    type: integer
                  minItems: 2
                  maxItems: 2
      tags:
        - profile
        - electricity
        
  /profile/{profileId}/solar:
    post:
      summary: Generated solar electricity data
      description: Get the corresponding generated solar electricity data of a profile.
      parameters:
        - $ref: '#/components/parameters/profileId'
      requestBody:
        $ref: '#/components/requestBodies/time_interval'
      responses:
        '200':
          description: 'success'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    type: integer
                  minItems: 2
                  maxItems: 2
      tags:
        - profile
        - electricity
  
  /data/sems:
    post:
      summary: Single Electricity Market Spot
      requestBody:
        $ref: '#/components/requestBodies/time_interval'
      responses:
        '200':
          description: 'success'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    type: integer
                  minItems: 2
                  maxItems: 2
      tags:
        - electricity
        
components:
  schemas:
    profile:
      type: object
      properties:
        id:
          type: integer
          description: the id of this profile
        user_id:
          type: integer
          description: the id of the owner of this profile
        name:
          type: string
          description: the name of the profile
        desc:
          type: string
          description: profile description
        start_time:
          type: string
          format: date-time
          description: the start time of data in this profile
        end_time:
          type: string
          format: date-time
          description: the start time of data in this profile
        lon:
          type: number
          description: lontitude
        lat:
          type: number
          description: latitude
        tech:
          type: 
          
          
  requestBodies:
    data_type: # TODO
      required: true
    time_interval:
      description: time interval. Note that the `step` property is enum type, which is not noted in the `exmaple value` tab
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              step:
                type: string
                description: time step
                enum: 
                 - 15m
                 - 30m
                 - 1d
                 - 1m
                 - 1y
              start_time:
                type: string
                format: date-time
              end_time:
                type: string
                format: date-time
          
  parameters:
    profileId:
      in: path
      name: profileId
      schema:
        type: integer
      required: true
      description: id of a profile

  
