name: auto-deploy
on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    ubuntu:
        runs-on: ubuntu-latest
                 
        steps:
            - name: install just
              uses: extractions/setup-just@v1
                  
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: '3.12'
                  cache: 'pip' # caching pip dependencies

            - name: python initialization
              run: |
                   python -m venv .venv
                   source .venv/bin/activate
                   pip install .

            - uses: actions/setup-node@v4
              with:
                  node-version: "lts/iron"
            
            - name: initialize project
              run: |
                  touch .justfile-env
                  source .venv/bin/activate
                  pip install --upgrade setuptools # fix `just trans`'s flask-babel error - ValueError: Unknown extraction method 'jinja2'
                  just initialize  # note that this command also can pre-populate the generated database
                  
            - name: build project
              run: just build

            - name: clean previous deployed files on server
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  password: ${{ secrets.REMOTE_PASS }}
                  port: ${{ secrets.REMOTE_PORT }}
                  script: |
                      rm -rf ~/website/comp3030j
                      rm -rf ~/website/instance

            - name: deploy the project
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  password: ${{ secrets.REMOTE_PASS }}
                  port: ${{ secrets.REMOTE_PORT }}
                  source: "comp3030j,instance,pyproject.toml"  # copy the whole config directory since it contains pre-populated database
                  target: ~/website

            - name: reload server service
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  password: ${{ secrets.REMOTE_PASS }}
                  port: ${{ secrets.REMOTE_PORT }}
                  script: |
                      cd ~/website
                      python -m venv .venv # if exists, python will do nothing
                      source .venv/bin/activate
                      pip install . # update dependencies
                      pip install gunicorn # install gunicorn
                      echo ${{secrets.REMOTE_PASS}} | sudo -S systemctl reload gunicorn


