name: auto-deploy
on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    ubuntu:
        runs-on: ubuntu-latest
        steps:
            -   name: install just
                uses: extractions/setup-just@v1
                with:
                    just-version: 1.24.0
            -   uses: actions/checkout@v4
            -   name: initialize
                run: npm install daisyui --4.7.3
            -   run: just build
            -   name: Setup SSH Key
                run: |
                    ls -la ./comp3030j
                    mkdir -p ~/.ssh
                    echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                    chmod 600 ~/.ssh/id_rsa
                    ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
                shell: bash
            -   name: Transfer document with SCP
                run: |
                    scp -r -i ssh_key ./comp3030j/* ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/student/website/comp3030j/
                    scp -r ./instance/config.py ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/student/website/instance/config.py
                shell: bash

            -   name: executing remote ssh commands using password
                uses: appleboy/ssh-action@v1.0.3
                with:
                    host: ${{ secrets.REMOTE_HOST }}
                    username: ${{ secrets.REMOTE_USER }}
                    password: ${{ secrets.REMOTE_PASS }}
                    port: 22
                    script: |
                        echo ${{ secrets.REMOTE_PASS }} | sudo -S systemctl reload gunicorn
